macro_rules! def {
    (__impl $name:tt) => {
        Builtin {
            name: $name,
            is_hidden: true,
            // Ignored.
            kind: BuiltinKind::Function,
        }
    };
    (__impl $name:tt $kind:tt) => {
        Builtin {
            name: $name,
            is_hidden: false,
            kind: BuiltinKind::$kind,
        }
    };
    ($($name:literal $(= $kind:tt)?,)*) => {
        phf::phf_map! {
            $($name => def!(__impl $name $($kind)?),)*
        }
    };
}

pub static BUILTINS: phf::Map<&'static str, Builtin> = def! {
    "__addErrorContext",
    "__all",
    "__any",
    "__appendContext",
    "__attrNames",
    "__attrValues",
    "__bitAnd",
    "__bitOr",
    "__bitXor",
    "__catAttrs",
    "__ceil",
    "__compareVersions",
    "__concatLists",
    "__concatMap",
    "__concatStringsSep",
    "__currentSystem",
    "__currentTime",
    "__deepSeq",
    "__div",
    "__elem",
    "__elemAt",
    "__fetchurl",
    "__filter",
    "__filterSource",
    "__findFile",
    "__floor",
    "__foldl'",
    "__fromJSON",
    "__functionArgs",
    "__genList",
    "__genericClosure",
    "__getAttr",
    "__getContext",
    "__getEnv",
    "__getFlake",
    "__groupBy",
    "__hasAttr",
    "__hasContext",
    "__hashFile",
    "__hashString",
    "__head",
    "__intersectAttrs",
    "__isAttrs",
    "__isBool",
    "__isFloat",
    "__isFunction",
    "__isInt",
    "__isList",
    "__isPath",
    "__isString",
    "__langVersion",
    "__length",
    "__lessThan",
    "__listToAttrs",
    "__mapAttrs",
    "__match",
    "__mul",
    "__nixPath",
    "__nixVersion",
    "__parseDrvName",
    "__partition",
    "__path",
    "__pathExists",
    "__readDir",
    "__readFile",
    "__replaceStrings",
    "__seq",
    "__sort",
    "__split",
    "__splitVersion",
    "__storeDir",
    "__storePath",
    "__stringLength",
    "__sub",
    "__substring",
    "__tail",
    "__toFile",
    "__toJSON",
    "__toPath",
    "__toXML",
    "__trace",
    "__traceVerbose",
    "__tryEval",
    "__typeOf",
    "__unsafeDiscardOutputDependency",
    "__unsafeDiscardStringContext",
    "__unsafeGetAttrPos",
    "__zipAttrsWith",
    "abort" = Function,
    "baseNameOf" = Function,
    "break" = Function,
    "builtins" = Attrset,
    "derivation" = Function,
    "derivationStrict" = Function,
    "dirOf" = Function,
    "false" = Const,
    "fetchGit" = Function,
    "fetchMercurial" = Function,
    "fetchTarball" = Function,
    "fetchTree" = Function,
    "fromTOML" = Function,
    "import" = Function,
    "isNull" = Function,
    "map" = Function,
    "null" = Const,
    "placeholder" = Function,
    "removeAttrs" = Function,
    "scopedImport" = Function,
    "throw" = Function,
    "toString" = Function,
    "true" = Const,
};

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Builtin {
    pub name: &'static str,
    pub is_hidden: bool,
    pub kind: BuiltinKind,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BuiltinKind {
    Const,
    Function,
    Attrset,
}
